version: '3'

services:
  backend:
    image: 'simple-crypto-market:local-dev'
    tty: true
    volumes:
      - './app:/app'
      - '/app/node_modules'
    environment:
      - NODE_ENV=development
    container_name: simple-crypto-market
