version: '3'

services:
  backend:
    image: 'simple-crypto-market:local-dev'
    tty: true
    volumes:
      - './app:/app'
    environment:
      - NODE_ENV=development
    ports:
    - 3000:3000
    container_name: simple-crypto-market
